package com.test.present.cp.case1;

import com.test.present.cp.ConstantPoolPresenterTestBase;
import org.junit.Before;
import org.junit.Test;

import java.io.IOException;
import java.util.List;

public class ListCpTest extends ConstantPoolPresenterTestBase {

    @Before
    public void prepare() throws IOException, ClassNotFoundException {
        buildRealLines(Class.forName("java.util.List"));
    }

    @Test
    public void test() {
        expectedLines = List.of(
                "    #4 = Utf8               java/util/Objects",
                "    #5 = Utf8               requireNonNull",
                "    #6 = Utf8               (Ljava/lang/Object;)Ljava/lang/Object;",
                "   #10 = Utf8               java/util/List",
                "   #11 = Utf8               listIterator",
                "   #12 = Utf8               ()Ljava/util/ListIterator;",
                "   #16 = Utf8               java/util/ListIterator",
                "   #17 = Utf8               hasNext",
                "   #18 = Utf8               ()Z",
                "   #21 = Utf8               next",
                "   #22 = Utf8               ()Ljava/lang/Object;",
                "   #26 = Utf8               java/util/function/UnaryOperator",
                "   #27 = Utf8               apply",
                "   #30 = Utf8               set",
                "   #31 = Utf8               (Ljava/lang/Object;)V",
                "   #34 = Utf8               toArray",
                "   #35 = Utf8               ()[Ljava/lang/Object;",
                "   #39 = Utf8               java/util/Arrays",
                "   #40 = Utf8               sort",
                "   #41 = Utf8               ([Ljava/lang/Object;Ljava/util/Comparator;)V",
                "   #43 = Utf8               java/util/RandomAccess",
                "   #45 = Utf8               java/util/AbstractList$RandomAccessSpliterator",
                "   #48 = Utf8               <init>",
                "   #49 = Utf8               (Ljava/util/List;)V",
                "   #51 = Utf8               java/util/Spliterator",
                "   #55 = Utf8               java/util/Spliterators",
                "   #56 = Utf8               spliterator",
                "   #57 = Utf8               (Ljava/util/Collection;I)Ljava/util/Spliterator;",
                "   #60 = Utf8               add",
                "   #61 = Utf8               (ILjava/lang/Object;)V",
                "   #64 = Utf8               (Ljava/lang/Object;)Z",
                "   #67 = Utf8               isEmpty",
                "   #69 = Utf8               java/util/NoSuchElementException",
                "   #72 = Utf8               ()V",
                "   #75 = Utf8               get",
                "   #76 = Utf8               (I)Ljava/lang/Object;",
                "   #79 = Utf8               size",
                "   #80 = Utf8               ()I",
                "   #83 = Utf8               remove",
                "   #87 = Utf8               java/util/ReverseOrderListView",
                "   #88 = Utf8               of",
                "   #89 = Utf8               (Ljava/util/List;Z)Ljava/util/List;",
                "   #93 = Utf8               java/util/ImmutableCollections",
                "   #94 = Utf8               EMPTY_LIST",
                "   #95 = Utf8               Ljava/util/ImmutableCollections$ListN;",
                "   #97 = Utf8               java/util/ImmutableCollections$List12",
                "  #102 = Utf8               (Ljava/lang/Object;Ljava/lang/Object;)V",
                "  #104 = Utf8               java/lang/Object",
                "  #107 = Utf8               listFromTrustedArray",
                "  #108 = Utf8               ([Ljava/lang/Object;)Ljava/util/List;",
                "  #111 = Utf8               listFromArray",
                "  #114 = Utf8               listCopy",
                "  #115 = Utf8               (Ljava/util/Collection;)Ljava/util/List;",
                "  #118 = Utf8               reversed",
                "  #119 = Utf8               ()Ljava/util/List;",
                "  #121 = Utf8               java/util/SequencedCollection",
                "  #122 = Utf8               contains",
                "  #123 = Utf8               iterator",
                "  #124 = Utf8               ()Ljava/util/Iterator;",
                "  #125 = Utf8               Signature",
                "  #126 = Utf8               ()Ljava/util/Iterator<TE;>;",
                "  #127 = Utf8               ([Ljava/lang/Object;)[Ljava/lang/Object;",
                "  #128 = Utf8               <T:Ljava/lang/Object;>([TT;)[TT;",
                "  #129 = Utf8               (TE;)Z",
                "  #130 = Utf8               containsAll",
                "  #131 = Utf8               (Ljava/util/Collection;)Z",
                "  #132 = Utf8               (Ljava/util/Collection<*>;)Z",
                "  #133 = Utf8               addAll",
                "  #134 = Utf8               (Ljava/util/Collection<+TE;>;)Z",
                "  #135 = Utf8               (ILjava/util/Collection;)Z",
                "  #136 = Utf8               (ILjava/util/Collection<+TE;>;)Z",
                "  #137 = Utf8               removeAll",
                "  #138 = Utf8               retainAll",
                "  #139 = Utf8               replaceAll",
                "  #140 = Utf8               (Ljava/util/function/UnaryOperator;)V",
                "  #141 = Utf8               Code",
                "  #142 = Utf8               LineNumberTable",
                "  #143 = Utf8               LocalVariableTable",
                "  #144 = Utf8               this",
                "  #145 = Utf8               Ljava/util/List;",
                "  #146 = Utf8               operator",
                "  #147 = Utf8               Ljava/util/function/UnaryOperator;",
                "  #148 = Utf8               li",
                "  #149 = Utf8               Ljava/util/ListIterator;",
                "  #150 = Utf8               LocalVariableTypeTable",
                "  #151 = Utf8               Ljava/util/List<TE;>;",
                "  #152 = Utf8               Ljava/util/function/UnaryOperator<TE;>;",
                "  #153 = Utf8               Ljava/util/ListIterator<TE;>;",
                "  #154 = Utf8               StackMapTable",
                "  #155 = Utf8               (Ljava/util/function/UnaryOperator<TE;>;)V",
                "  #156 = Utf8               (Ljava/util/Comparator;)V",
                "  #157 = Utf8               e",
                "  #158 = Utf8               Ljava/lang/Object;",
                "  #159 = Utf8               c",
                "  #160 = Utf8               Ljava/util/Comparator;",
                "  #161 = Utf8               a",
                "  #162 = Utf8               [Ljava/lang/Object;",
                "  #163 = Utf8               i",
                "  #164 = Utf8               Ljava/util/Comparator<-TE;>;",
                "  #166 = Utf8               java/util/Comparator",
                "  #168 = Utf8               (Ljava/util/Comparator<-TE;>;)V",
                "  #169 = Utf8               clear",
                "  #170 = Utf8               equals",
                "  #171 = Utf8               hashCode",
                "  #172 = Utf8               (I)TE;",
                "  #173 = Utf8               (ILjava/lang/Object;)Ljava/lang/Object;",
                "  #174 = Utf8               (ITE;)TE;",
                "  #175 = Utf8               (ITE;)V",
                "  #176 = Utf8               indexOf",
                "  #177 = Utf8               (Ljava/lang/Object;)I",
                "  #178 = Utf8               lastIndexOf",
                "  #179 = Utf8               ()Ljava/util/ListIterator<TE;>;",
                "  #180 = Utf8               (I)Ljava/util/ListIterator;",
                "  #181 = Utf8               (I)Ljava/util/ListIterator<TE;>;",
                "  #182 = Utf8               subList",
                "  #183 = Utf8               (II)Ljava/util/List;",
                "  #184 = Utf8               (II)Ljava/util/List<TE;>;",
                "  #185 = Utf8               ()Ljava/util/Spliterator;",
                "  #186 = Utf8               ()Ljava/util/Spliterator<TE;>;",
                "  #187 = Utf8               addFirst",
                "  #188 = Utf8               TE;",
                "  #189 = Utf8               (TE;)V",
                "  #190 = Utf8               addLast",
                "  #191 = Utf8               getFirst",
                "  #192 = Utf8               ()TE;",
                "  #193 = Utf8               getLast",
                "  #194 = Utf8               removeFirst",
                "  #195 = Utf8               removeLast",
                "  #196 = Utf8               ()Ljava/util/List<TE;>;",
                "  #197 = Utf8               <E:Ljava/lang/Object;>()Ljava/util/List<TE;>;",
                "  #198 = Utf8               (Ljava/lang/Object;)Ljava/util/List;",
                "  #199 = Utf8               e1",
                "  #200 = Utf8               <E:Ljava/lang/Object;>(TE;)Ljava/util/List<TE;>;",
                "  #201 = Utf8               (Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/List;",
                "  #202 = Utf8               e2",
                "  #203 = Utf8               <E:Ljava/lang/Object;>(TE;TE;)Ljava/util/List<TE;>;",
                "  #204 = Utf8               (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/List;",
                "  #205 = Utf8               e3",
                "  #206 = Utf8               <E:Ljava/lang/Object;>(TE;TE;TE;)Ljava/util/List<TE;>;",
                "  #207 = Utf8               (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/List;",
                "  #208 = Utf8               e4",
                "  #209 = Utf8               <E:Ljava/lang/Object;>(TE;TE;TE;TE;)Ljava/util/List<TE;>;",
                "  #210 = Utf8               (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/List;",
                "  #211 = Utf8               e5",
                "  #212 = Utf8               <E:Ljava/lang/Object;>(TE;TE;TE;TE;TE;)Ljava/util/List<TE;>;",
                "  #213 = Utf8               (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/List;",
                "  #214 = Utf8               e6",
                "  #215 = Utf8               <E:Ljava/lang/Object;>(TE;TE;TE;TE;TE;TE;)Ljava/util/List<TE;>;",
                "  #216 = Utf8               (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/List;",
                "  #217 = Utf8               e7",
                "  #218 = Utf8               <E:Ljava/lang/Object;>(TE;TE;TE;TE;TE;TE;TE;)Ljava/util/List<TE;>;",
                "  #219 = Utf8               (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/List;",
                "  #220 = Utf8               e8",
                "  #221 = Utf8               <E:Ljava/lang/Object;>(TE;TE;TE;TE;TE;TE;TE;TE;)Ljava/util/List<TE;>;",
                "  #222 = Utf8               (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/List;",
                "  #223 = Utf8               e9",
                "  #224 = Utf8               <E:Ljava/lang/Object;>(TE;TE;TE;TE;TE;TE;TE;TE;TE;)Ljava/util/List<TE;>;",
                "  #225 = Utf8               (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/List;",
                "  #226 = Utf8               e10",
                "  #227 = Utf8               <E:Ljava/lang/Object;>(TE;TE;TE;TE;TE;TE;TE;TE;TE;TE;)Ljava/util/List<TE;>;",
                "  #228 = Utf8               list",
                "  #229 = Utf8               elements",
                "  #230 = Utf8               [TE;",
                "  #231 = Utf8               <E:Ljava/lang/Object;>([TE;)Ljava/util/List<TE;>;",
                "  #232 = Utf8               RuntimeVisibleAnnotations",
                "  #233 = Utf8               Ljava/lang/SafeVarargs;",
                "  #234 = Utf8               copyOf",
                "  #235 = Utf8               coll",
                "  #236 = Utf8               Ljava/util/Collection;",
                "  #237 = Utf8               Ljava/util/Collection<+TE;>;",
                "  #238 = Utf8               <E:Ljava/lang/Object;>(Ljava/util/Collection<+TE;>;)Ljava/util/List<TE;>;",
                "  #239 = Utf8               ()Ljava/util/SequencedCollection;",
                "  #240 = Utf8               <E:Ljava/lang/Object;>Ljava/lang/Object;Ljava/util/SequencedCollection<TE;>;",
                "  #241 = Utf8               SourceFile",
                "  #242 = Utf8               List.java",
                "  #243 = Utf8               InnerClasses",
                "  #245 = Utf8               java/util/AbstractList",
                "  #246 = Utf8               RandomAccessSpliterator",
                "  #248 = Utf8               java/util/ImmutableCollections$ListN",
                "  #249 = Utf8               ListN",
                "  #250 = Utf8               List12"
        );
    }
}
