package com.test.presenter.cp.caseAll;

import com.study.constants.ConstantKind;
import com.test.annotations.ExpectedConstantKind;
import com.test.annotations.GeneratedBy;
import com.test.presenter.cp.ConstantPoolPresenterTestBase;
import com.test.presenter.cp.ConstantPoolTestGenerator;
import org.junit.BeforeClass;
import org.junit.Test;

import java.io.IOException;
import java.util.List;

@GeneratedBy(ConstantPoolTestGenerator.class)
public class ListCpTest extends ConstantPoolPresenterTestBase {

    @BeforeClass
    public static void prepare() throws IOException, ClassNotFoundException {
        buildRealLines(Class.forName("java.util.List"));
    }

    @ExpectedConstantKind(ConstantKind.CONSTANT_Class)
    @ExpectedConstantKind(ConstantKind.CONSTANT_Fieldref)
    @ExpectedConstantKind(ConstantKind.CONSTANT_Methodref)
    @ExpectedConstantKind(ConstantKind.CONSTANT_InterfaceMethodref)
    @ExpectedConstantKind(ConstantKind.CONSTANT_NameAndType)
    @ExpectedConstantKind(ConstantKind.CONSTANT_Utf8)
    @Test
    public void test() {
        expectedLines = List.of(
                "    #1 = Methodref          #2.#3         // java/util/Objects.requireNonNull:(Ljava/lang/Object;)Ljava/lang/Object;",
                "    #2 = Class              #4            // java/util/Objects",
                "    #3 = NameAndType        #5:#6         // requireNonNull:(Ljava/lang/Object;)Ljava/lang/Object;",
                "    #4 = Utf8               java/util/Objects",
                "    #5 = Utf8               requireNonNull",
                "    #6 = Utf8               (Ljava/lang/Object;)Ljava/lang/Object;",
                "    #7 = InterfaceMethodref #8.#9         // java/util/List.listIterator:()Ljava/util/ListIterator;",
                "    #8 = Class              #10           // java/util/List",
                "    #9 = NameAndType        #11:#12       // listIterator:()Ljava/util/ListIterator;",
                "   #10 = Utf8               java/util/List",
                "   #11 = Utf8               listIterator",
                "   #12 = Utf8               ()Ljava/util/ListIterator;",
                "   #13 = InterfaceMethodref #14.#15       // java/util/ListIterator.hasNext:()Z",
                "   #14 = Class              #16           // java/util/ListIterator",
                "   #15 = NameAndType        #17:#18       // hasNext:()Z",
                "   #16 = Utf8               java/util/ListIterator",
                "   #17 = Utf8               hasNext",
                "   #18 = Utf8               ()Z",
                "   #19 = InterfaceMethodref #14.#20       // java/util/ListIterator.next:()Ljava/lang/Object;",
                "   #20 = NameAndType        #21:#22       // next:()Ljava/lang/Object;",
                "   #21 = Utf8               next",
                "   #22 = Utf8               ()Ljava/lang/Object;",
                "   #23 = InterfaceMethodref #24.#25       // java/util/function/UnaryOperator.apply:(Ljava/lang/Object;)Ljava/lang/Object;",
                "   #24 = Class              #26           // java/util/function/UnaryOperator",
                "   #25 = NameAndType        #27:#6        // apply:(Ljava/lang/Object;)Ljava/lang/Object;",
                "   #26 = Utf8               java/util/function/UnaryOperator",
                "   #27 = Utf8               apply",
                "   #28 = InterfaceMethodref #14.#29       // java/util/ListIterator.set:(Ljava/lang/Object;)V",
                "   #29 = NameAndType        #30:#31       // set:(Ljava/lang/Object;)V",
                "   #30 = Utf8               set",
                "   #31 = Utf8               (Ljava/lang/Object;)V",
                "   #32 = InterfaceMethodref #8.#33        // java/util/List.toArray:()[Ljava/lang/Object;",
                "   #33 = NameAndType        #34:#35       // toArray:()[Ljava/lang/Object;",
                "   #34 = Utf8               toArray",
                "   #35 = Utf8               ()[Ljava/lang/Object;",
                "   #36 = Methodref          #37.#38       // java/util/Arrays.sort:([Ljava/lang/Object;Ljava/util/Comparator;)V",
                "   #37 = Class              #39           // java/util/Arrays",
                "   #38 = NameAndType        #40:#41       // sort:([Ljava/lang/Object;Ljava/util/Comparator;)V",
                "   #39 = Utf8               java/util/Arrays",
                "   #40 = Utf8               sort",
                "   #41 = Utf8               ([Ljava/lang/Object;Ljava/util/Comparator;)V",
                "   #42 = Class              #43           // java/util/RandomAccess",
                "   #43 = Utf8               java/util/RandomAccess",
                "   #44 = Class              #45           // java/util/AbstractList$RandomAccessSpliterator",
                "   #45 = Utf8               java/util/AbstractList$RandomAccessSpliterator",
                "   #46 = Methodref          #44.#47       // java/util/AbstractList$RandomAccessSpliterator.\"<init>\":(Ljava/util/List;)V",
                "   #47 = NameAndType        #48:#49       // \"<init>\":(Ljava/util/List;)V",
                "   #48 = Utf8               <init>",
                "   #49 = Utf8               (Ljava/util/List;)V",
                "   #50 = Class              #51           // java/util/Spliterator",
                "   #51 = Utf8               java/util/Spliterator",
                "   #52 = Methodref          #53.#54       // java/util/Spliterators.spliterator:(Ljava/util/Collection;I)Ljava/util/Spliterator;",
                "   #53 = Class              #55           // java/util/Spliterators",
                "   #54 = NameAndType        #56:#57       // spliterator:(Ljava/util/Collection;I)Ljava/util/Spliterator;",
                "   #55 = Utf8               java/util/Spliterators",
                "   #56 = Utf8               spliterator",
                "   #57 = Utf8               (Ljava/util/Collection;I)Ljava/util/Spliterator;",
                "   #58 = InterfaceMethodref #8.#59        // java/util/List.add:(ILjava/lang/Object;)V",
                "   #59 = NameAndType        #60:#61       // add:(ILjava/lang/Object;)V",
                "   #60 = Utf8               add",
                "   #61 = Utf8               (ILjava/lang/Object;)V",
                "   #62 = InterfaceMethodref #8.#63        // java/util/List.add:(Ljava/lang/Object;)Z",
                "   #63 = NameAndType        #60:#64       // add:(Ljava/lang/Object;)Z",
                "   #64 = Utf8               (Ljava/lang/Object;)Z",
                "   #65 = InterfaceMethodref #8.#66        // java/util/List.isEmpty:()Z",
                "   #66 = NameAndType        #67:#18       // isEmpty:()Z",
                "   #67 = Utf8               isEmpty",
                "   #68 = Class              #69           // java/util/NoSuchElementException",
                "   #69 = Utf8               java/util/NoSuchElementException",
                "   #70 = Methodref          #68.#71       // java/util/NoSuchElementException.\"<init>\":()V",
                "   #71 = NameAndType        #48:#72       // \"<init>\":()V",
                "   #72 = Utf8               ()V",
                "   #73 = InterfaceMethodref #8.#74        // java/util/List.get:(I)Ljava/lang/Object;",
                "   #74 = NameAndType        #75:#76       // get:(I)Ljava/lang/Object;",
                "   #75 = Utf8               get",
                "   #76 = Utf8               (I)Ljava/lang/Object;",
                "   #77 = InterfaceMethodref #8.#78        // java/util/List.size:()I",
                "   #78 = NameAndType        #79:#80       // size:()I",
                "   #79 = Utf8               size",
                "   #80 = Utf8               ()I",
                "   #81 = InterfaceMethodref #8.#82        // java/util/List.remove:(I)Ljava/lang/Object;",
                "   #82 = NameAndType        #83:#76       // remove:(I)Ljava/lang/Object;",
                "   #83 = Utf8               remove",
                "   #84 = Methodref          #85.#86       // java/util/ReverseOrderListView.of:(Ljava/util/List;Z)Ljava/util/List;",
                "   #85 = Class              #87           // java/util/ReverseOrderListView",
                "   #86 = NameAndType        #88:#89       // of:(Ljava/util/List;Z)Ljava/util/List;",
                "   #87 = Utf8               java/util/ReverseOrderListView",
                "   #88 = Utf8               of",
                "   #89 = Utf8               (Ljava/util/List;Z)Ljava/util/List;",
                "   #90 = Fieldref           #91.#92       // java/util/ImmutableCollections.EMPTY_LIST:Ljava/util/ImmutableCollections$ListN;",
                "   #91 = Class              #93           // java/util/ImmutableCollections",
                "   #92 = NameAndType        #94:#95       // EMPTY_LIST:Ljava/util/ImmutableCollections$ListN;",
                "   #93 = Utf8               java/util/ImmutableCollections",
                "   #94 = Utf8               EMPTY_LIST",
                "   #95 = Utf8               Ljava/util/ImmutableCollections$ListN;",
                "   #96 = Class              #97           // java/util/ImmutableCollections$List12",
                "   #97 = Utf8               java/util/ImmutableCollections$List12",
                "   #98 = Methodref          #96.#99       // java/util/ImmutableCollections$List12.\"<init>\":(Ljava/lang/Object;)V",
                "   #99 = NameAndType        #48:#31       // \"<init>\":(Ljava/lang/Object;)V",
                "  #100 = Methodref          #96.#101      // java/util/ImmutableCollections$List12.\"<init>\":(Ljava/lang/Object;Ljava/lang/Object;)V",
                "  #101 = NameAndType        #48:#102      // \"<init>\":(Ljava/lang/Object;Ljava/lang/Object;)V",
                "  #102 = Utf8               (Ljava/lang/Object;Ljava/lang/Object;)V",
                "  #103 = Class              #104          // java/lang/Object",
                "  #104 = Utf8               java/lang/Object",
                "  #105 = Methodref          #91.#106      // java/util/ImmutableCollections.listFromTrustedArray:([Ljava/lang/Object;)Ljava/util/List;",
                "  #106 = NameAndType        #107:#108     // listFromTrustedArray:([Ljava/lang/Object;)Ljava/util/List;",
                "  #107 = Utf8               listFromTrustedArray",
                "  #108 = Utf8               ([Ljava/lang/Object;)Ljava/util/List;",
                "  #109 = Methodref          #91.#110      // java/util/ImmutableCollections.listFromArray:([Ljava/lang/Object;)Ljava/util/List;",
                "  #110 = NameAndType        #111:#108     // listFromArray:([Ljava/lang/Object;)Ljava/util/List;",
                "  #111 = Utf8               listFromArray",
                "  #112 = Methodref          #91.#113      // java/util/ImmutableCollections.listCopy:(Ljava/util/Collection;)Ljava/util/List;",
                "  #113 = NameAndType        #114:#115     // listCopy:(Ljava/util/Collection;)Ljava/util/List;",
                "  #114 = Utf8               listCopy",
                "  #115 = Utf8               (Ljava/util/Collection;)Ljava/util/List;",
                "  #116 = InterfaceMethodref #8.#117       // java/util/List.reversed:()Ljava/util/List;",
                "  #117 = NameAndType        #118:#119     // reversed:()Ljava/util/List;",
                "  #118 = Utf8               reversed",
                "  #119 = Utf8               ()Ljava/util/List;",
                "  #120 = Class              #121          // java/util/SequencedCollection",
                "  #121 = Utf8               java/util/SequencedCollection",
                "  #122 = Utf8               contains",
                "  #123 = Utf8               iterator",
                "  #124 = Utf8               ()Ljava/util/Iterator;",
                "  #125 = Utf8               Signature",
                "  #126 = Utf8               ()Ljava/util/Iterator<TE;>;",
                "  #127 = Utf8               ([Ljava/lang/Object;)[Ljava/lang/Object;",
                "  #128 = Utf8               <T:Ljava/lang/Object;>([TT;)[TT;",
                "  #129 = Utf8               (TE;)Z",
                "  #130 = Utf8               containsAll",
                "  #131 = Utf8               (Ljava/util/Collection;)Z",
                "  #132 = Utf8               (Ljava/util/Collection<*>;)Z",
                "  #133 = Utf8               addAll",
                "  #134 = Utf8               (Ljava/util/Collection<+TE;>;)Z",
                "  #135 = Utf8               (ILjava/util/Collection;)Z",
                "  #136 = Utf8               (ILjava/util/Collection<+TE;>;)Z",
                "  #137 = Utf8               removeAll",
                "  #138 = Utf8               retainAll",
                "  #139 = Utf8               replaceAll",
                "  #140 = Utf8               (Ljava/util/function/UnaryOperator;)V",
                "  #141 = Utf8               Code",
                "  #142 = Utf8               LineNumberTable",
                "  #143 = Utf8               LocalVariableTable",
                "  #144 = Utf8               this",
                "  #145 = Utf8               Ljava/util/List;",
                "  #146 = Utf8               operator",
                "  #147 = Utf8               Ljava/util/function/UnaryOperator;",
                "  #148 = Utf8               li",
                "  #149 = Utf8               Ljava/util/ListIterator;",
                "  #150 = Utf8               LocalVariableTypeTable",
                "  #151 = Utf8               Ljava/util/List<TE;>;",
                "  #152 = Utf8               Ljava/util/function/UnaryOperator<TE;>;",
                "  #153 = Utf8               Ljava/util/ListIterator<TE;>;",
                "  #154 = Utf8               StackMapTable",
                "  #155 = Utf8               (Ljava/util/function/UnaryOperator<TE;>;)V",
                "  #156 = Utf8               (Ljava/util/Comparator;)V",
                "  #157 = Utf8               e",
                "  #158 = Utf8               Ljava/lang/Object;",
                "  #159 = Utf8               c",
                "  #160 = Utf8               Ljava/util/Comparator;",
                "  #161 = Utf8               a",
                "  #162 = Utf8               [Ljava/lang/Object;",
                "  #163 = Utf8               i",
                "  #164 = Utf8               Ljava/util/Comparator<-TE;>;",
                "  #165 = Class              #166          // java/util/Comparator",
                "  #166 = Utf8               java/util/Comparator",
                "  #167 = Class              #162          // \"[Ljava/lang/Object;\"",
                "  #168 = Utf8               (Ljava/util/Comparator<-TE;>;)V",
                "  #169 = Utf8               clear",
                "  #170 = Utf8               equals",
                "  #171 = Utf8               hashCode",
                "  #172 = Utf8               (I)TE;",
                "  #173 = Utf8               (ILjava/lang/Object;)Ljava/lang/Object;",
                "  #174 = Utf8               (ITE;)TE;",
                "  #175 = Utf8               (ITE;)V",
                "  #176 = Utf8               indexOf",
                "  #177 = Utf8               (Ljava/lang/Object;)I",
                "  #178 = Utf8               lastIndexOf",
                "  #179 = Utf8               ()Ljava/util/ListIterator<TE;>;",
                "  #180 = Utf8               (I)Ljava/util/ListIterator;",
                "  #181 = Utf8               (I)Ljava/util/ListIterator<TE;>;",
                "  #182 = Utf8               subList",
                "  #183 = Utf8               (II)Ljava/util/List;",
                "  #184 = Utf8               (II)Ljava/util/List<TE;>;",
                "  #185 = Utf8               ()Ljava/util/Spliterator;",
                "  #186 = Utf8               ()Ljava/util/Spliterator<TE;>;",
                "  #187 = Utf8               addFirst",
                "  #188 = Utf8               TE;",
                "  #189 = Utf8               (TE;)V",
                "  #190 = Utf8               addLast",
                "  #191 = Utf8               getFirst",
                "  #192 = Utf8               ()TE;",
                "  #193 = Utf8               getLast",
                "  #194 = Utf8               removeFirst",
                "  #195 = Utf8               removeLast",
                "  #196 = Utf8               ()Ljava/util/List<TE;>;",
                "  #197 = Utf8               <E:Ljava/lang/Object;>()Ljava/util/List<TE;>;",
                "  #198 = Utf8               (Ljava/lang/Object;)Ljava/util/List;",
                "  #199 = Utf8               e1",
                "  #200 = Utf8               <E:Ljava/lang/Object;>(TE;)Ljava/util/List<TE;>;",
                "  #201 = Utf8               (Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/List;",
                "  #202 = Utf8               e2",
                "  #203 = Utf8               <E:Ljava/lang/Object;>(TE;TE;)Ljava/util/List<TE;>;",
                "  #204 = Utf8               (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/List;",
                "  #205 = Utf8               e3",
                "  #206 = Utf8               <E:Ljava/lang/Object;>(TE;TE;TE;)Ljava/util/List<TE;>;",
                "  #207 = Utf8               (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/List;",
                "  #208 = Utf8               e4",
                "  #209 = Utf8               <E:Ljava/lang/Object;>(TE;TE;TE;TE;)Ljava/util/List<TE;>;",
                "  #210 = Utf8               (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/List;",
                "  #211 = Utf8               e5",
                "  #212 = Utf8               <E:Ljava/lang/Object;>(TE;TE;TE;TE;TE;)Ljava/util/List<TE;>;",
                "  #213 = Utf8               (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/List;",
                "  #214 = Utf8               e6",
                "  #215 = Utf8               <E:Ljava/lang/Object;>(TE;TE;TE;TE;TE;TE;)Ljava/util/List<TE;>;",
                "  #216 = Utf8               (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/List;",
                "  #217 = Utf8               e7",
                "  #218 = Utf8               <E:Ljava/lang/Object;>(TE;TE;TE;TE;TE;TE;TE;)Ljava/util/List<TE;>;",
                "  #219 = Utf8               (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/List;",
                "  #220 = Utf8               e8",
                "  #221 = Utf8               <E:Ljava/lang/Object;>(TE;TE;TE;TE;TE;TE;TE;TE;)Ljava/util/List<TE;>;",
                "  #222 = Utf8               (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/List;",
                "  #223 = Utf8               e9",
                "  #224 = Utf8               <E:Ljava/lang/Object;>(TE;TE;TE;TE;TE;TE;TE;TE;TE;)Ljava/util/List<TE;>;",
                "  #225 = Utf8               (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/List;",
                "  #226 = Utf8               e10",
                "  #227 = Utf8               <E:Ljava/lang/Object;>(TE;TE;TE;TE;TE;TE;TE;TE;TE;TE;)Ljava/util/List<TE;>;",
                "  #228 = Utf8               list",
                "  #229 = Utf8               elements",
                "  #230 = Utf8               [TE;",
                "  #231 = Utf8               <E:Ljava/lang/Object;>([TE;)Ljava/util/List<TE;>;",
                "  #232 = Utf8               RuntimeVisibleAnnotations",
                "  #233 = Utf8               Ljava/lang/SafeVarargs;",
                "  #234 = Utf8               copyOf",
                "  #235 = Utf8               coll",
                "  #236 = Utf8               Ljava/util/Collection;",
                "  #237 = Utf8               Ljava/util/Collection<+TE;>;",
                "  #238 = Utf8               <E:Ljava/lang/Object;>(Ljava/util/Collection<+TE;>;)Ljava/util/List<TE;>;",
                "  #239 = Utf8               ()Ljava/util/SequencedCollection;",
                "  #240 = Utf8               <E:Ljava/lang/Object;>Ljava/lang/Object;Ljava/util/SequencedCollection<TE;>;",
                "  #241 = Utf8               SourceFile",
                "  #242 = Utf8               List.java",
                "  #243 = Utf8               InnerClasses",
                "  #244 = Class              #245          // java/util/AbstractList",
                "  #245 = Utf8               java/util/AbstractList",
                "  #246 = Utf8               RandomAccessSpliterator",
                "  #247 = Class              #248          // java/util/ImmutableCollections$ListN",
                "  #248 = Utf8               java/util/ImmutableCollections$ListN",
                "  #249 = Utf8               ListN",
                "  #250 = Utf8               List12"
        );
    }
}
